name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.35.1-jammy
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - name: Install Dependencies
        run: yarn install
      - name: Start
        run: yarn start
      - uses: actions/upload-artifact@v3
        with:
          name: screens
